// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8SHA7sLOczRTDXLzCpaDUQT9Z9LgCUyg',
    appId: '1:293110607839:web:5788d003ddb500eb1b1e6a',
    messagingSenderId: '293110607839',
    projectId: 'lovecount-eb812',
    authDomain: 'lovecount-eb812.firebaseapp.com',
    databaseURL: 'https://lovecount-eb812.firebaseio.com',
    storageBucket: 'lovecount-eb812.appspot.com',
    measurementId: 'G-ND8TXGLE0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVWsqAmJ4UppmtpPMlnpNuSfnXOpbvXgE',
    appId: '1:293110607839:android:01417214ba4dc5671b1e6a',
    messagingSenderId: '293110607839',
    projectId: 'lovecount-eb812',
    databaseURL: 'https://lovecount-eb812.firebaseio.com',
    storageBucket: 'lovecount-eb812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzd_Pdgu5t87JPIUMpzY0rVZ40ZonIAZU',
    appId: '1:293110607839:ios:4e5d3a882cf896841b1e6a',
    messagingSenderId: '293110607839',
    projectId: 'lovecount-eb812',
    databaseURL: 'https://lovecount-eb812.firebaseio.com',
    storageBucket: 'lovecount-eb812.appspot.com',
    androidClientId: '293110607839-5so1e74grjleqjhrgrn9k7rl6jmf4llu.apps.googleusercontent.com',
    iosClientId: '293110607839-9i5e3tu72vtaa4o9tj95622lq9eq43q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLovecount',
  );
}
